### PR TITLE
Add branch protection rules to all repos

### LINKED ISSUE #4: Add branch protection rules
We (the [Security Team](https://www.eclipse.org/security/team/) at the EF) would like to help our projects to increase their enable security posture by applying basic branch protection rules for the repos in their GitHub organization. For that purpose we would like to illustrate the different options that you have so that you can create PRs yourself that fit your needs.

### PR DESCRIPTION
**Pull request by mbarbero**
No mandatory pull request, no require approving review count.

Fixes #4

### CODE REVIEW

**Comment by mbarbero** [comment]
@fredg02, WDYT?

**Comment by fredg02** [comment]
LGTM

**Comment by mbarbero** [comment]
> LGTM

please approve the PR via GH mechanism :D

**Review by fredg02 — APPROVED** [review]

**Comment by netomi** [comment]
changes have been applied.

**Comment by fredg02** [comment]
Status checks prevented direct pushes. Thanks to @netomi for disabling them in https://github.com/eclipse-cbi/.eclipsefdn/pull/6.

**Pull request merged**
